export const DUMMY_NFT_LIST = [
  {
    img: "images/NFT/snoop.png",
    artist: "Puddy Penguin",
    name: "dobby-dob",
    price: "1.79",
    crypto: "ETH",
  },
  {
    img: "images/NFT/eminem.png",
    artist: "machineBunKelly",
    name: "god.",
    price: "20",
    crypto: "ETH",
  },
  {
    img: "images/NFT/disco.png",
    artist: "beker",
    name: "disco",
    price: "6.02",
    crypto: "SOL",
  },
  {
    img: "images/NFT/monke.png",
    artist: "urg0",
    name: "MONKE",
    price: "0.69",
    crypto: "ETH",
  },
  {
    img: "images/NFT/moonbirds.png",
    artist: "p2231s241",
    name: "flappy",
    price: "1",
    crypto: "AVAX",
  },

  {
    img: "images/NFT/monalisa.png",
    artist: "ldv",
    name: "lonamisa",
    price: "1",
    crypto: "ADA",
  },
  {
    img: "images/NFT/deGods.png",
    artist: "artist",
    name: "de214g0d1s",
    price: "3.10",
    crypto: "SOL",
  },
  {
    img: "images/NFT/pug.png",
    artist: "urg0",
    name: "luigi",
    price: "100",
    crypto: "ETH",
  },
  {
    img: "images/NFT/art1.png",
    artist: "p1epe",
    name: "POTATOPePe",
    price: "12.3",
    crypto: "CAKE",
    category: ["art"],
  },
  {
    img: "images/NFT/art2.png",
    artist: "prichett",
    name: "!ears",
    price: "18.3",
    crypto: "CAKE",
    category: ["art"],
  },
  {
    img: "images/NFT/art3.png",
    artist: "mc0h",
    name: "gismondA",
    price: "2.13",
    crypto: "AVAX",
    category: ["art"],
  },
  {
    img: "images/NFT/art4.png",
    artist: "mc0h",
    name: "daydream.",
    price: "9.02",
    crypto: "AVAX",
    category: ["art"],
  },
  {
    img: "images/NFT/art5.png",
    artist: "milf",
    name: "90b",
    price: "120.3",
    crypto: "MANA",
    category: ["art"],
  },
  {
    img: "images/NFT/art6.png",
    artist: "d1c4pr10",
    name: "sp0000000",
    price: "1.3",
    crypto: "ETH",
    category: ["art"],
  },
  {
    img: "images/NFT/art7.png",
    artist: "d1c4pr10",
    name: "monaWisa",
    price: "4",
    crypto: "ETH",
    category: ["art"],
  },
  {
    img: "images/NFT/art8.png",
    artist: "d1c4pr10",
    name: "HOlDisa",
    price: "12.3",
    crypto: "CAKE",
    category: ["art"],
  },
  {
    img: "images/NFT/freud1.png",
    artist: "urg0",
    name: "c1ga'r",
    price: "20",
    crypto: "ETH",
    category: ["freud"],
  },
  {
    img: "images/NFT/freud2.png",
    artist: "urg0",
    name: "c2ga'r",
    price: "25",
    crypto: "ETH",
    category: ["freud"],
  },
  {
    img: "images/NFT/freud3.png",
    artist: "urg0",
    name: ".oidipus.",
    price: "200",
    crypto: "ETH",
    category: ["freud"],
  },
  {
    img: "images/NFT/freud4.png",
    artist: "machineBunKelly",
    name: "lil freud",
    price: "80.5",
    crypto: "AVAX",
    category: ["freud"],
  },
  {
    img: "images/NFT/freud5.png",
    artist: "lllllllll2314llllllll",
    name: "1*<est",
    price: "5",
    crypto: "SOL",
    category: ["freud"],
  },
  {
    img: "images/NFT/freud6.png",
    artist: "lllllllll2314llllllll",
    name: "gigmd1212!!2",
    price: "12",
    crypto: "CAKE",
    category: ["freud"],
  },
  {
    img: "images/NFT/freud7.png",
    artist: "d1c4pr10",
    name: "m0mmy",
    price: "2",
    crypto: "ETH",
    category: ["freud"],
  },

  {
    img: "images/NFT/monke1.png",
    artist: "allen",
    name: "M001",
    price: "0.5",
    crypto: "ETH",
    category: ["monke", "animal"],
  },
  {
    img: "images/NFT/monke2.png",
    artist: "allen",
    name: "M002",
    price: "0.2",
    crypto: "ETH",
    category: ["monke", "animal"],
  },
  {
    img: "images/NFT/monke3.png",
    artist: "allen",
    name: "M003",
    price: "3.5",
    crypto: "ETH",
    category: ["monke", "animal"],
  },
  {
    img: "images/NFT/monke4.png",
    artist: "user998153",
    name: "fu",
    price: "3",
    crypto: "ETH",
    category: ["monke", "animal"],
  },
  {
    img: "images/NFT/monke5.png",
    artist: "anon",
    name: "fckngmonke010101",
    price: "2",
    crypto: "AVAX",
    category: ["monke", "animal"],
  },
  {
    img: "images/NFT/monke6.png",
    artist: "anon",
    name: "fckngmonke020202",
    price: "2",
    crypto: "AVAX",
    category: ["monke", "animal"],
  },
  {
    img: "images/NFT/monke7.png",
    artist: "anon",
    name: "fckngBTCmonke",
    price: "1",
    crypto: "AVAX",
    category: ["monke", "animal"],
  },
  {
    img: "images/NFT/monke8.png",
    artist: "hz.mohammed571",
    name: "mekka",
    price: "250",
    crypto: "ETH",
    category: ["monke", "animal"],
  },
  {
    img: "images/NFT/monke9.png",
    artist: "hz.mohammed571",
    name: "medina",
    price: "0.5",
    crypto: "ETH",
    category: ["monke", "animal"],
  },
  {
    img: "images/NFT/monke10.png",
    artist: "randy marsh",
    name: "farmarsh",
    price: "14",
    crypto: "CAKE",
    category: ["monke", "animal", "weed"],
  },
  {
    img: "images/NFT/monke11.png",
    artist: "randy marsh",
    name: "d-o-doubleg",
    price: "71",
    crypto: "ETH",
    category: ["monke", "animal", "weed"],
  },
  {
    img: "images/NFT/monke12.png",
    artist: "kngw",
    name: "4ogK2",
    price: "7",
    crypto: "CAKE",
    category: ["monke", "animal"],
  },
  {
    img: "images/NFT/monke13.png",
    artist: "urg0",
    name: "?bono?",
    price: "96",
    crypto: "ETH",
    category: ["monke", "animal", "racing"],
  },
  {
    img: "images/NFT/monke14.png",
    artist: "urg0",
    name: "wallboro",
    price: "50.5555",
    crypto: "ETH",
    category: ["monke", "animal", "racing"],
  },
  {
    img: "images/NFT/monke15.png",
    artist: "fizbo",
    name: "h1opsf-2321s-3f",
    price: "1",
    crypto: "CAKE",
    category: ["monke", "animal"],
  },
  {
    img: "images/NFT/monke16.png",
    artist: "sfartist",
    name: "duffy.",
    price: "4",
    crypto: "MANA",
    category: ["monke", "animal", "simpsons", "TV Series"],
  },
  {
    img: "images/NFT/monke17.png",
    artist: "sfartist",
    name: "ddoge",
    price: "2",
    crypto: "MANA",
    category: ["monke", "animal", "simpsons", "TV Series"],
  },
  {
    img: "images/NFT/monke18.png",
    artist: "sfartist",
    name: "**b*",
    price: "4",
    crypto: "MANA",
    category: ["monke", "animal", "simpsons"],
  },
  {
    img: "images/NFT/monke19.png",
    artist: "213",
    name: "Smonkeyy",
    price: "20",
    crypto: "ETH",
    category: ["monke", "animal", "weed"],
  },
  {
    img: "images/NFT/monke20.png",
    artist: "213",
    name: "doctor",
    price: "4",
    crypto: "MANA",
    category: ["monke", "animal", "simpsons"],
  },
  {
    img: "images/NFT/monke21.png",
    artist: "lllllllll2314llllllll",
    name: "robot",
    price: "100",
    crypto: "ETH",
    category: ["monke", "animal", "sport"],
  },
  {
    img: "images/NFT/monke22.png",
    artist: "prichett",
    name: "lizbo",
    price: "10",
    crypto: "SOL",
    category: ["monke", "animal", "art"],
  },
  {
    img: "images/NFT/monke23.png",
    artist: "prichett",
    name: "-mp-",
    price: "9.27",
    crypto: "SOL",
    category: ["monke", "animal", "art"],
  },
  {
    img: "images/NFT/monke24.png",
    artist: "42810948129048",
    name: "q+",
    price: "58.25",
    crypto: "CAKE",
    category: ["monke", "animal"],
  },
  {
    img: "images/NFT/monke25.png",
    artist: "42810948129048",
    name: "salah",
    price: "120",
    crypto: "CAKE",
    category: ["monke", "animal", "art"],
  },
  {
    img: "images/NFT/monke26.png",
    artist: "basay",
    name: "l-rev",
    price: "0.0000001",
    crypto: "ETH",
    category: ["monke", "animal"],
  },
  {
    img: "images/NFT/monke27.png",
    artist: "lllllllll2314llllllll",
    name: "<gfr>",
    price: "20",
    crypto: "MANA",
    category: ["monke", "animal"],
  },
  {
    img: "images/NFT/monke28.png",
    artist: "pasha",
    name: "46",
    price: "11",
    crypto: "SOL",
    category: ["monke", "animal"],
  },
  {
    img: "images/NFT/monke29.png",
    artist: "prichett",
    name: "6$",
    price: "6",
    crypto: "SOL",
    category: ["monke", "animal"],
  },
  {
    img: "images/NFT/monke30.png",
    artist: "moses",
    name: "moneyM",
    price: "1000",
    crypto: "ETH",
    category: ["monke", "animal"],
  },
  {
    img: "images/NFT/ozgun.png",
    artist: "urg0",
    name: "oçöç",
    price: "0.00000000000031",
    crypto: "ETH",
    category: ["monke", "animal"],
  },
  {
    img: "images/NFT/monke31.png",
    artist: "ei0606",
    name: "barriers",
    price: "4",
    crypto: "AVAX",
    category: ["monke", "animal", "art", "racing"],
  },
  {
    img: "images/NFT/monke32.png",
    artist: "urg0",
    name: "tyres",
    price: "44",
    crypto: "ETH",
    category: ["monke", "animal", "art", "racing"],
  },
  {
    img: "images/NFT/monke33.png",
    artist: "hamverbot",
    name: "ad21ad21",
    price: "9",
    crypto: "CAKE",
    category: ["monke", "animal", "art", "racing"],
  },
  {
    img: "images/NFT/monke34.png",
    artist: "hamverbot",
    name: "sadmonke",
    price: "2007",
    crypto: "CAKE",
    category: ["monke", "animal", "art", "racing"],
  },
  {
    img: "images/NFT/monke35.png",
    artist: "hamverbot",
    name: "austin",
    price: "0.2",
    crypto: "AVAX",
    category: ["monke", "animal", "art", "racing"],
  },
  {
    img: "images/NFT/monke36.png",
    artist: "sfartist",
    name: "hjs",
    price: "20",
    crypto: "AVAX",
    category: ["monke", "animal", "art", "weed", "simpsons", "TV Series"],
  },
  {
    img: "images/NFT/others2.png",
    artist: "mylf",
    name: "bbw",
    price: "1",
    crypto: "ETH",
    category: ["other"],
  },
  {
    img: "images/NFT/others3.png",
    artist: "mylf",
    name: "black!",
    price: "0.5",
    crypto: "ETH",
    category: ["other"],
  },
  {
    img: "images/NFT/others4.png",
    artist: "mylf",
    name: "f.???????",
    price: "69",
    crypto: "AVAX",
    category: ["other"],
  },
  {
    img: "images/NFT/penguin1.png",
    artist: "mip",
    name: "pingu in black",
    price: "0.35",
    crypto: "ETH",
    category: ["penguin"],
  },
  {
    img: "images/NFT/penguin2.png",
    artist: "mip",
    name: "bread",
    price: "0.255",
    crypto: "ETH",
    category: ["penguin"],
  },
  {
    img: "images/NFT/penguin3.png",
    artist: "mip",
    name: "n*gg*s in tokyo.",
    price: "4.15",
    crypto: "ETH",
    category: ["penguin"],
  },
  {
    img: "images/NFT/penguin4.png",
    artist: "11",
    name: "checo",
    price: "0.35",
    crypto: "ETH",
    category: ["penguin"],
  },
  {
    img: "images/NFT/penguin5.png",
    artist: "mip",
    name: "vercetti",
    price: "66.6",
    crypto: "ETH",
    category: ["penguin"],
  },
  {
    img: "images/NFT/penguin6.png",
    artist: "mip",
    name: "pingu 2n black",
    price: "1.36",
    crypto: "ETH",
    category: ["penguin"],
  },
  {
    img: "images/NFT/penguin7.png",
    artist: "a-mini",
    name: "AAA12",
    price: "369",
    crypto: "AVAX",
    category: ["penguin"],
  },
  {
    img: "images/NFT/penguin8.png",
    artist: "a-mini",
    name: "t?!?!1",
    price: "104.5",
    crypto: "AVAX",
    category: ["penguin"],
  },
  {
    img: "images/NFT/penguin9.png",
    artist: "vitalik",
    name: "murder",
    price: "12",
    crypto: "CAKE",
    category: ["penguin"],
  },
  {
    img: "images/NFT/penguin10.png",
    artist: "11",
    name: "el-paso",
    price: "0.35",
    crypto: "ETH",
    category: ["penguin"],
  },
  {
    img: "images/NFT/racing1.png",
    artist: "urg0",
    name: "gone.",
    price: "1.44",
    crypto: "ETH",
    category: ["racing"],
  },
  {
    img: "images/NFT/racing2.png",
    artist: "11",
    name: "bahrainP1",
    price: "0.1111",
    crypto: "ETH",
    category: ["racing"],
  },
  {
    img: "images/NFT/racing3.png",
    artist: "urg0",
    name: "loser",
    price: "1.44",
    crypto: "ETH",
    category: ["racing"],
  },
  {
    img: "images/NFT/racing4.png",
    artist: "urg0",
    name: "honey-badger",
    price: "10.03",
    crypto: "ETH",
    category: ["racing"],
  },
  {
    img: "images/NFT/racing5.png",
    artist: "bono",
    name: "my",
    price: "10.03",
    crypto: "ETH",
    category: ["racing"],
  },
  {
    img: "images/NFT/racing6.png",
    artist: "urg0",
    name: "f-2004",
    price: "??.??",
    crypto: "ETH",
    category: ["racing"],
  },
  {
    img: "images/NFT/racing7.png",
    artist: "urg0",
    name: "keepfighting",
    price: "??.??",
    crypto: "ETH",
    category: ["racing"],
  },
  {
    img: "images/NFT/racing8.png",
    artist: "urg0",
    name: "are",
    price: "20.44",
    crypto: "ETH",
    category: ["racing"],
  },
  {
    img: "images/NFT/racing9.png",
    artist: "urg0",
    name: "_doctor",
    price: "6.81",
    crypto: "ETH",
    category: ["racing"],
  },
  {
    img: "images/NFT/randomGuy.png",
    artist: "urg0",
    name: "mumble",
    price: "0.01",
    crypto: "AVAX",
    category: ["other"],
  },
  {
    img: "images/NFT/southPark1.png",
    artist: "butters",
    name: "19SC2",
    price: "19.2",
    crypto: "SOL",
    category: ["TV Series", "South Park"],
  },
  {
    img: "images/NFT/southPark2.png",
    artist: "butters",
    name: "19SC2.1",
    price: "19.2",
    crypto: "SOL",
    category: ["TV Series", "South Park"],
  },
  {
    img: "images/NFT/southPark3.png",
    artist: "butters",
    name: "big-mac",
    price: "105.99",
    crypto: "SOL",
    category: ["TV Series", "South Park"],
  },
  {
    img: "images/NFT/southPark4.png",
    artist: "butters",
    name: "self",
    price: "250",
    crypto: "SOL",
    category: ["TV Series", "South Park"],
  },
  {
    img: "images/NFT/southPark5.png",
    artist: "butters",
    name: "farm",
    price: "42.24",
    crypto: "SOL",
    category: ["TV Series", "South Park"],
  },
  {
    img: "images/NFT/southPark1.png",
    artist: "detective",
    name: "star23!21s",
    price: "80",
    crypto: "CAKE",
    category: ["TV Series", "South Park"],
  },
  {
    img: "images/NFT/southPark7.png",
    artist: "b-rabbit",
    name: "D2LB",
    price: "313",
    crypto: "SOL",
    category: ["TV Series", "South Park"],
  },
];

export const randomNFTList = [];

while (randomNFTList.length < 30) {
  const randomIndex = Math.floor(Math.random() * DUMMY_NFT_LIST.length);
  const randomObject = DUMMY_NFT_LIST[randomIndex];

  if (!randomNFTList.includes(randomObject)) {
    randomNFTList.push(randomObject);
  }
}
